systems:
  - darwin/amd64
  - darwin/arm64
  - linux/amd64
  - windows/amd64
dependencies:
  gh:
    template: origin#gh
    vars:
      version: 2.88.1
  gofumpt:
    template: origin#gofumpt
    vars:
      version: 0.9.2
  golangci-lint:
    template: origin#golangci-lint
    vars:
      version: 2.11.3
  goreleaser:
    template: origin#goreleaser
    vars:
      version: 2.14.3
  handcrafted:
    template: origin#handcrafted
    vars:
      version: 0.0.0
  jq:
    template: origin#jq
    vars:
      version: 1.8.1
  shellcheck:
    template: origin#shellcheck
    vars:
      version: 0.11.0
  shfmt:
    template: origin#shfmt
    vars:
      version: 3.13.0
templates:
  origin#gh:
    homepage: https://github.com/cli/cli
    description: GitHub’s official command line tool
    url: https://github.com/cli/cli/releases/download/v{{.version}}/gh_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: gh_{{.version}}_{{.os}}_{{.arch}}/bin/gh{{.archivePathSuffix}}
    bin: gh
    vars:
      archivePathSuffix: ""
      urlSuffix: .zip
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          archive_path: bin/gh{{.archivePathSuffix}}
          vars:
            archivePathSuffix: .exe
      - matcher:
          os:
            - linux
        dependency:
          vars:
            urlSuffix: .tar.gz
      - matcher:
          os:
            - darwin
          version:
            - < 2.28.0
        dependency:
          vars:
            urlSuffix: .tar.gz
    substitutions:
      os:
        darwin: macOS
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
      - windows/arm64
    required_vars:
      - version
  origin#gofumpt:
    url: https://github.com/mvdan/gofumpt/releases/download/v{{.version}}/gofumpt_v{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: gofumpt_v{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    bin: gofumpt
    vars:
      archivePathSuffix: ""
      urlSuffix: ""
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            urlSuffix: .exe
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
    required_vars:
      - version
  origin#golangci-lint:
    url: https://github.com/golangci/golangci-lint/releases/download/v{{.version}}/golangci-lint-{{.version}}-{{.os}}-{{.arch}}{{.urlsuffix}}
    archive_path: golangci-lint-{{.version}}-{{.os}}-{{.arch}}/golangci-lint{{.archivepathsuffix}}
    bin: golangci-lint
    link: true
    vars:
      archivepathsuffix: ""
      urlsuffix: .tar.gz
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            archivepathsuffix: .exe
            urlsuffix: .zip
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
      - freebsd/386
      - freebsd/amd64
      - linux/mips64
      - linux/mips64le
      - linux/s390x
      - linux/ppc64le
    required_vars:
      - version
  origin#goreleaser:
    homepage: https://github.com/goreleaser/goreleaser
    description: Deliver Go binaries as fast and easily as possible
    url: https://github.com/goreleaser/goreleaser/releases/download/v{{.version}}/goreleaser_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: goreleaser{{.archivePathSuffix}}
    bin: goreleaser
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            archivePathSuffix: .exe
            urlSuffix: .zip
          substitutions:
            arch:
              "386": i386
              amd64: x86_64
            os:
              windows: Windows
    substitutions:
      arch:
        "386": i386
        amd64: x86_64
      os:
        darwin: Darwin
        linux: Linux
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - linux/ppc64
      - windows/386
      - windows/amd64
      - windows/arm64
    required_vars:
      - version
  origin#handcrafted:
    homepage: https://github.com/willabides/handcrafted
    description: lists non-generated go files in a package
    url: https://github.com/WillAbides/handcrafted/releases/download/v{{.version}}/handcrafted_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: handcrafted{{.archivePathSuffix}}
    bin: handcrafted
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            archivePathSuffix: .exe
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
      - windows/arm64
    required_vars:
      - version
  origin#jq:
    homepage: https://github.com/stedolan/jq
    description: Command-line JSON processor
    url: https://github.com/stedolan/jq/releases/download/jq-{{.version}}/jq-{{.os}}{{.arch}}{{.extension}}
    archive_path: jq-{{.os}}{{.arch}}{{.extension}}
    bin: jq
    vars:
      extension: ""
    overrides:
      - matcher:
          arch:
            - amd64
            - arm64
          os:
            - darwin
        dependency:
          url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
          archive_path: jq-osx-amd64
      - matcher:
          os:
            - windows
        dependency:
          vars:
            extension: .exe
    substitutions:
      arch:
        "386": "32"
        amd64: "64"
      os:
        windows: win
    systems:
      - linux/386
      - linux/amd64
      - darwin/amd64
      - darwin/arm64
      - windows/386
      - windows/amd64
    required_vars:
      - version
  origin#shellcheck:
    url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.{{.os}}.{{.arch}}.tar.xz
    archive_path: shellcheck-v{{.version}}/shellcheck
    bin: shellcheck
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.zip
          archive_path: shellcheck.exe
      - matcher:
          arch:
            - arm64
          os:
            - darwin
        dependency:
          vars:
            arch: amd64
    substitutions:
      arch:
        amd64: x86_64
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/amd64
      - windows/amd64
    required_vars:
      - version
  origin#shfmt:
    homepage: https://github.com/mvdan/sh
    description: A shell parser, formatter, and interpreter with bash support; includes shfmt
    url: https://github.com/mvdan/sh/releases/download/v{{.version}}/shfmt_v{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: shfmt_v{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    bin: shfmt
    vars:
      archivePathSuffix: ""
      urlSuffix: ""
    overrides:
      - matcher:
          os:
            - windows
        dependency:
          vars:
            urlSuffix: .exe
    systems:
      - darwin/amd64
      - darwin/arm64
      - linux/386
      - linux/amd64
      - linux/arm64
      - windows/386
      - windows/amd64
    required_vars:
      - version
template_sources:
  origin: https://raw.githubusercontent.com/WillAbides/bindown-templates/master/bindown.yml
url_checksums:
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_darwin_amd64.tar.gz: df5dbf9c8b282d8209a8baddfe3410c5b3ace87bdce808fce0a0d49356c9ff4d
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_darwin_arm64.tar.gz: c03133084f87e064f9801d4b2a9739be755fcee5875382f4da0fc10cd8306dfb
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_linux_amd64.tar.gz: 1a7885a9854d2455dce1be3bc19f2d61a61ebdc99e2a98e4969ab1965c2a64ad
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_windows_amd64.tar.gz: 5ce8cddc9bdbd19adde3104397d698ecca7eb8ad2ac540cc709a15821f9b2609
  https://github.com/cli/cli/releases/download/v2.88.1/gh_2.88.1_linux_amd64.tar.gz: 36352a993b97e9758793cdb87f9ba674bd6d88c914488e122be78a1962203803
  https://github.com/cli/cli/releases/download/v2.88.1/gh_2.88.1_macOS_amd64.zip: ff0fc4bdb9699f0c02e5bcdcbd09d0f8e4c4659aa5d30bcd39a3557ed7379b2e
  https://github.com/cli/cli/releases/download/v2.88.1/gh_2.88.1_macOS_arm64.zip: bdbeed4821d450ef0d14821d856c05b308ab449fbf60527f298d96fbf5d2447b
  https://github.com/cli/cli/releases/download/v2.88.1/gh_2.88.1_windows_amd64.zip: 8fdaac525d8919f9f8c265f99ffa26189e5f1fd3a35636adad4fd890a141a555
  https://github.com/golangci/golangci-lint/releases/download/v2.11.3/golangci-lint-2.11.3-darwin-amd64.tar.gz: f93bda1f2cc981fd1326464020494be62f387bbf262706e1b3b644e5afacc440
  https://github.com/golangci/golangci-lint/releases/download/v2.11.3/golangci-lint-2.11.3-darwin-arm64.tar.gz: 30ee39979c516b9d1adca289a3f93429d130c4c0fda5e57d637850894221f6cc
  https://github.com/golangci/golangci-lint/releases/download/v2.11.3/golangci-lint-2.11.3-linux-amd64.tar.gz: 87bb8cddbcc825d5778b64e8a91b46c0526b247f4e2f2904dea74ec7450475d1
  https://github.com/golangci/golangci-lint/releases/download/v2.11.3/golangci-lint-2.11.3-windows-amd64.zip: cd42e890176bc5cfeb36225a77e66b9410ddd3a59a03551e23f6b210d29e1f67
  https://github.com/goreleaser/goreleaser/releases/download/v2.14.3/goreleaser_Darwin_arm64.tar.gz: 6dae42fecaed39f36d0ac9ce98f36ee14804e483f5c1446e205796ac91b7be4e
  https://github.com/goreleaser/goreleaser/releases/download/v2.14.3/goreleaser_Darwin_x86_64.tar.gz: d8fcc408826058986df90950ce2824ed037e57e3229eb23dcf0badc8d23123bc
  https://github.com/goreleaser/goreleaser/releases/download/v2.14.3/goreleaser_Linux_x86_64.tar.gz: dc7faeeeb6da8bdfda788626263a4ae725892a8c7504b975c3234127d4a44579
  https://github.com/goreleaser/goreleaser/releases/download/v2.14.3/goreleaser_Windows_x86_64.zip: 3deea8ff471aa258a2d99f3e5302971d7028647ae8ddaf103257a8113e485a31
  https://github.com/koalaman/shellcheck/releases/download/v0.11.0/shellcheck-v0.11.0.darwin.x86_64.tar.xz: 3c89db4edcab7cf1c27bff178882e0f6f27f7afdf54e859fa041fca10febe4c6
  https://github.com/koalaman/shellcheck/releases/download/v0.11.0/shellcheck-v0.11.0.linux.x86_64.tar.xz: 8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198
  https://github.com/koalaman/shellcheck/releases/download/v0.11.0/shellcheck-v0.11.0.zip: 8a4e35ab0b331c85d73567b12f2a444df187f483e5079ceffa6bda1faa2e740e
  https://github.com/mvdan/gofumpt/releases/download/v0.9.2/gofumpt_v0.9.2_darwin_amd64: 4172b912ec514038605f334fef9ed7b3f12ca3e40024cb0a622eab3073a55e57
  https://github.com/mvdan/gofumpt/releases/download/v0.9.2/gofumpt_v0.9.2_darwin_arm64: c241fb742599a6cb0563d7377f59def65d451b23dd718dbc6ddf4ab5e695e8f1
  https://github.com/mvdan/gofumpt/releases/download/v0.9.2/gofumpt_v0.9.2_linux_amd64: 72cf61b12fef91eab6df6db4a4284f30616b5ead330112e28a1fa1cb15e57339
  https://github.com/mvdan/gofumpt/releases/download/v0.9.2/gofumpt_v0.9.2_windows_amd64.exe: 067236b55a8ef4547ddc7d78fbb7a38169de15bab02a1763cde6a132c59dd35c
  https://github.com/mvdan/sh/releases/download/v3.13.0/shfmt_v3.13.0_darwin_amd64: b6890a0009abf71d36d7c536ad56e3132c547ceb77cd5d5ee62b3469ab4e9417
  https://github.com/mvdan/sh/releases/download/v3.13.0/shfmt_v3.13.0_darwin_arm64: 650970603b5946dc6041836ddcfa7a19d99b5da885e4687f64575508e99cf718
  https://github.com/mvdan/sh/releases/download/v3.13.0/shfmt_v3.13.0_linux_amd64: 70aa99784703a8d6569bbf0b1e43e1a91906a4166bf1a79de42050a6d0de7551
  https://github.com/mvdan/sh/releases/download/v3.13.0/shfmt_v3.13.0_windows_amd64.exe: 62241aaf6b0ca236f8625d8892784b73fa67ad40bc677a1ad1a64ae395f6a7d5
  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64: 5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef
  https://github.com/stedolan/jq/releases/download/jq-1.8.1/jq-linux64: 020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d
  https://github.com/stedolan/jq/releases/download/jq-1.8.1/jq-win64.exe: 23cb60a1354eed6bcc8d9b9735e8c7b388cd1fdcb75726b93bc299ef22dd9334
