systems:
- darwin/amd64
- darwin/arm64
- linux/amd64
- windows/amd64
dependencies:
  gofumpt:
    template: origin#gofumpt
    vars:
      version: 0.5.0
  golangci-lint:
    template: origin#golangci-lint
    vars:
      version: 1.51.2
  goreleaser:
    template: origin#goreleaser
    vars:
      version: 1.18.2
  handcrafted:
    template: origin#handcrafted
    vars:
      version: 0.0.0
  semver-next:
    template: origin#semver-next
    vars:
      version: 0.11.3
  shellcheck:
    template: origin#shellcheck
    vars:
      version: 0.9.0
templates:
  origin#gofumpt:
    url: https://github.com/mvdan/gofumpt/releases/download/v{{.version}}/gofumpt_v{{.version}}_{{.os}}_{{.arch}}{{.suffix}}
    archive_path: gofumpt_v{{.version}}_{{.os}}_{{.arch}}{{.suffix}}
    bin: gofumpt{{.suffix}}
    vars:
      suffix: ""
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        vars:
          suffix: .exe
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm
    - linux/arm64
    - windows/386
    - windows/amd64
  origin#golangci-lint:
    url: https://github.com/golangci/golangci-lint/releases/download/v{{.version}}/golangci-lint-{{.version}}-{{.os}}-{{.arch}}{{.urlsuffix}}
    archive_path: golangci-lint-{{.version}}-{{.os}}-{{.arch}}/golangci-lint{{.archivepathsuffix}}
    bin: golangci-lint
    link: true
    vars:
      archivepathsuffix: ""
      urlsuffix: .tar.gz
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        vars:
          archivepathsuffix: .exe
          urlsuffix: .zip
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm64
    - windows/386
    - windows/amd64
    - freebsd/386
    - freebsd/amd64
    - linux/mips64
    - linux/mips64le
    - linux/s390x
    - linux/ppc64le
  origin#goreleaser:
    homepage: https://github.com/goreleaser/goreleaser
    description: Deliver Go binaries as fast and easily as possible
    url: https://github.com/goreleaser/goreleaser/releases/download/v{{.version}}/goreleaser_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: goreleaser{{.archivePathSuffix}}
    bin: goreleaser
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        vars:
          archivePathSuffix: .exe
          urlSuffix: .zip
        substitutions:
          arch:
            "386": i386
            amd64: x86_64
          os:
            windows: Windows
    substitutions:
      arch:
        "386": i386
        amd64: x86_64
      os:
        darwin: Darwin
        linux: Linux
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm64
    - linux/ppc64
    - windows/386
    - windows/amd64
    - windows/arm64
  origin#handcrafted:
    homepage: https://github.com/willabides/handcrafted
    description: lists non-generated go files in a package
    url: https://github.com/WillAbides/handcrafted/releases/download/v{{.version}}/handcrafted_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: handcrafted{{.archivePathSuffix}}
    bin: handcrafted
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        vars:
          archivePathSuffix: .exe
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm64
    - windows/386
    - windows/amd64
    - windows/arm64
  origin#semver-next:
    homepage: https://github.com/WillAbides/semver-next
    url: https://github.com/WillAbides/semver-next/releases/download/v{{.version}}/semver-next_{{.version}}_{{.os}}_{{.arch}}{{.urlSuffix}}
    archive_path: semver-next{{.archivePathSuffix}}
    bin: semver-next
    vars:
      archivePathSuffix: ""
      urlSuffix: .tar.gz
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        vars:
          archivePathSuffix: .exe
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm64
    - windows/386
    - windows/amd64
    - windows/arm64
  origin#shellcheck:
    url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.{{.os}}.{{.arch}}.tar.xz
    archive_path: shellcheck-v{{.version}}/shellcheck
    bin: shellcheck
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.zip
        archive_path: shellcheck.exe
    - matcher:
        arch:
        - arm64
        os:
        - darwin
      dependency:
        vars:
          arch: amd64
    substitutions:
      arch:
        amd64: x86_64
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/amd64
    - windows/amd64
template_sources:
  origin: https://raw.githubusercontent.com/WillAbides/bindown-templates/master/bindown.yml
url_checksums:
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_darwin_amd64.tar.gz: df5dbf9c8b282d8209a8baddfe3410c5b3ace87bdce808fce0a0d49356c9ff4d
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_darwin_arm64.tar.gz: c03133084f87e064f9801d4b2a9739be755fcee5875382f4da0fc10cd8306dfb
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_linux_amd64.tar.gz: 1a7885a9854d2455dce1be3bc19f2d61a61ebdc99e2a98e4969ab1965c2a64ad
  https://github.com/WillAbides/handcrafted/releases/download/v0.0.0/handcrafted_0.0.0_windows_amd64.tar.gz: 5ce8cddc9bdbd19adde3104397d698ecca7eb8ad2ac540cc709a15821f9b2609
  https://github.com/WillAbides/semver-next/releases/download/v0.11.3/semver-next_0.11.3_darwin_amd64.tar.gz: 4f7fbb6b16600bdbd049250a1389a01e08a1490f4ceb864b78a19be9f4f74e75
  https://github.com/WillAbides/semver-next/releases/download/v0.11.3/semver-next_0.11.3_darwin_arm64.tar.gz: 44a42c6c347f3968c8db2cdf1a1ce61ffa3c0db0af5ae7febc21f19a1ff96afb
  https://github.com/WillAbides/semver-next/releases/download/v0.11.3/semver-next_0.11.3_linux_amd64.tar.gz: 35b024a2ace9977672e78979f13e9bc48973c4a8f19ae7517f1796fbb91a6c11
  https://github.com/WillAbides/semver-next/releases/download/v0.11.3/semver-next_0.11.3_windows_amd64.tar.gz: 0a5e3e743daf3e2eb1e8b41f4787472be1791ac9157c40ac2e9ff39c85eb8730
  https://github.com/golangci/golangci-lint/releases/download/v1.51.2/golangci-lint-1.51.2-darwin-amd64.tar.gz: 0549cbaa2df451cf3a2011a9d73a9cb127784d26749d9cd14c9f4818af104d44
  https://github.com/golangci/golangci-lint/releases/download/v1.51.2/golangci-lint-1.51.2-darwin-arm64.tar.gz: 36e69882205a0e42a63ad57ec3015639c11051e03f0beb9cf7949c6451408960
  https://github.com/golangci/golangci-lint/releases/download/v1.51.2/golangci-lint-1.51.2-linux-amd64.tar.gz: 4de479eb9d9bc29da51aec1834e7c255b333723d38dbd56781c68e5dddc6a90b
  https://github.com/golangci/golangci-lint/releases/download/v1.51.2/golangci-lint-1.51.2-windows-amd64.zip: aac163d9bf3f79457399c2852cfae550cd250f23df9b324966f9c54e767ff42d
  https://github.com/goreleaser/goreleaser/releases/download/v1.18.2/goreleaser_Darwin_arm64.tar.gz: 7eec9f4d0b86b2c9c9f6af1770a11315998bd4d4617633b0a73eeb036e97393e
  https://github.com/goreleaser/goreleaser/releases/download/v1.18.2/goreleaser_Darwin_x86_64.tar.gz: 95338eed333347152e23837b68a8c6ce0c62b9f5abb68bd5b4b08178766400b9
  https://github.com/goreleaser/goreleaser/releases/download/v1.18.2/goreleaser_Linux_x86_64.tar.gz: 811e0c63e347f78f3c8612a19ca8eeb564eb45f0265ce3f38aec39c8fdbcfa10
  https://github.com/goreleaser/goreleaser/releases/download/v1.18.2/goreleaser_Windows_x86_64.zip: 4b67f9a0159dc4f6a19fdea46eda506d58efe9e9d01aebc6ee39c9e9c14f9715
  https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.x86_64.tar.xz: 7d3730694707605d6e60cec4efcb79a0632d61babc035aa16cda1b897536acf5
  https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.xz: 700324c6dd0ebea0117591c6cc9d7350d9c7c5c287acbad7630fa17b1d4d9e2f
  https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.zip: ae58191b1ea4ffd9e5b15da9134146e636440302ce3e2f46863e8d71c8be1bbb
  https://github.com/mvdan/gofumpt/releases/download/v0.5.0/gofumpt_v0.5.0_darwin_amd64: 870f05a23541aad3d20d208a3ea17606169a240f608ac1cf987426198c14b2ed
  https://github.com/mvdan/gofumpt/releases/download/v0.5.0/gofumpt_v0.5.0_darwin_arm64: f2df95d5fad8498ad8eeb0be8abdb8bb8d05e8130b332cb69751dfd090fabac4
  https://github.com/mvdan/gofumpt/releases/download/v0.5.0/gofumpt_v0.5.0_linux_amd64: 759c6ab56bfbf62cafb35944aef1e0104a117e0aebfe44816fd79ef4b28521e4
  https://github.com/mvdan/gofumpt/releases/download/v0.5.0/gofumpt_v0.5.0_windows_amd64.exe: c9ca0a8a95c2ead0a009a349d5a326e385f5f15a96b084e11c4a7c1cb86b694b
