systems:
- darwin/amd64
- darwin/arm64
- linux/amd64
dependencies:
  gofumpt:
    template: origin#gofumpt
    vars:
      version: 0.4.0
  golangci-lint:
    template: origin#golangci-lint
    vars:
      version: 1.50.1
  shellcheck:
    template: origin#shellcheck
    vars:
      version: 0.8.0
templates:
  origin#gofumpt:
    url: https://github.com/mvdan/gofumpt/releases/download/v{{.version}}/gofumpt_v{{.version}}_{{.os}}_{{.arch}}{{.suffix}}
    archive_path: gofumpt_v{{.version}}_{{.os}}_{{.arch}}{{.suffix}}
    bin: gofumpt{{.suffix}}
    vars:
      suffix: ""
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        vars:
          suffix: .exe
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm
    - linux/arm64
    - windows/386
    - windows/amd64
  origin#golangci-lint:
    url: https://github.com/golangci/golangci-lint/releases/download/v{{.version}}/golangci-lint-{{.version}}-{{.os}}-{{.arch}}{{.urlsuffix}}
    archive_path: golangci-lint-{{.version}}-{{.os}}-{{.arch}}/golangci-lint{{.archivepathsuffix}}
    bin: golangci-lint
    link: true
    vars:
      archivepathsuffix: ""
      urlsuffix: .tar.gz
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        vars:
          archivepathsuffix: .exe
          urlsuffix: .zip
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/386
    - linux/amd64
    - linux/arm64
    - windows/386
    - windows/amd64
    - freebsd/386
    - freebsd/amd64
    - linux/mips64
    - linux/mips64le
    - linux/s390x
    - linux/ppc64le
  origin#shellcheck:
    url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.{{.os}}.{{.arch}}.tar.xz
    archive_path: shellcheck-v{{.version}}/shellcheck
    bin: shellcheck
    required_vars:
    - version
    overrides:
    - matcher:
        os:
        - windows
      dependency:
        url: https://github.com/koalaman/shellcheck/releases/download/v{{.version}}/shellcheck-v{{.version}}.zip
        archive_path: shellcheck.exe
    - matcher:
        arch:
        - arm64
        os:
        - darwin
      dependency:
        vars:
          arch: amd64
    substitutions:
      arch:
        amd64: x86_64
    systems:
    - darwin/amd64
    - darwin/arm64
    - linux/amd64
    - windows/amd64
template_sources:
  origin: https://raw.githubusercontent.com/WillAbides/bindown-templates/master/bindown.yml
url_checksums:
  https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-darwin-amd64.tar.gz: 0f615fb8c364f6e4a213f2ed2ff7aa1fc2b208addf29511e89c03534067bbf57
  https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-darwin-arm64.tar.gz: 3ca9753d7804b34f9165427fbe339dbea69bd80be8a10e3f02c6037393b2e1c4
  https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.tar.gz: 4ba1dc9dbdf05b7bdc6f0e04bdfe6f63aa70576f51817be1b2540bbce017b69a
  https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.darwin.x86_64.tar.xz: e065d4afb2620cc8c1d420a9b3e6243c84ff1a693c1ff0e38f279c8f31e86634
  https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz: ab6ee1b178f014d1b86d1e24da20d1139656c8b0ed34d2867fbb834dad02bf0a
  https://github.com/mvdan/gofumpt/releases/download/v0.4.0/gofumpt_v0.4.0_darwin_amd64: 3f550baa6d4c071b01e9c68b9308bd2ca3bae6b3b09d203f19ed8626ee0fe487
  https://github.com/mvdan/gofumpt/releases/download/v0.4.0/gofumpt_v0.4.0_darwin_arm64: 768263452749a3a3cabf412f29f8a14e8bbdc7f6c6471427e977eebc6592ddb8
  https://github.com/mvdan/gofumpt/releases/download/v0.4.0/gofumpt_v0.4.0_linux_amd64: d3ca535e6b0b230a9c4f05a3ec54e358336b5e7474d239c15514e63a0b2a8041
