#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

nwo="$GITHUB_REPOSITORY"
if [ -z "$nwo" ]; then
  nwo=$(git remote get-url origin)
  nwo=${nwo#"git@github.com:"}
  nwo=${nwo#"https://github.com/"}
  nwo=${nwo%".git"}
fi

reponame=$(echo "$nwo" | cut -d "/" -f2)
downcased_reponame="$(echo "$reponame" | tr '[:upper:]' '[:lower:]')"

template_reponame="goproject-tmpl"
sed -i '' "s|$template_reponame|$reponame|g" README.md

template_modulename="github.com/willabides/goproject-tmpl"
modulename="$(echo "github.com/$nwo" | tr '[:upper:]' '[:lower:]')"
sed -i '' "s|$template_modulename|$modulename|g" go.mod

template_pkgname="goprojecttmpl"
pkgname="$(echo "$reponame" | tr '[:upper:]' '[:lower:]' | sed 's/-//g')"
sed -i '' "s|$template_pkgname|$pkgname|g" goproject-tmpl.go
sed -i '' "s|$template_pkgname|$pkgname|g" goproject-tmpl_test.go

mv goproject-tmpl.go "$downcased_reponame.go"
mv goproject-tmpl_test.go "${downcased_reponame}_test.go"
rm script/apply-template
