#!/bin/sh
#/ script/bindown runs bindown with the given arguments

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

mkdir -p bin

[ -f bin/bindown ] || sh -c "$(
  curl -sfL https://github.com/WillAbides/bindown/releases/download/v4.4.8/bootstrap-bindown.sh
)"

exec bin/bindown "$@"
