#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

script/bindown -q install gofumpt
script/bindown -q install handcrafted

git ls-files -o -c --exclude-standard '*.go' |
  bin/handcrafted |
  xargs bin/gofumpt -w -extra
