#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

if [ -f script/goproject-tmpl ]; then
  usag_sub="$(
    cat << EOF
<!--- start usage output --->

\`\`\`
$(COLUMNS=100 script/goproject-tmpl --help)
\`\`\`

<!--- end usage output --->
EOF
  )"
else
  # If we have no script/goproject-tmpl, this must not be a cli project, so make the usage output empty.
  usag_sub="$(
    cat << EOF
<!--- start usage output --->
<!--- end usage output --->
EOF
  )"
fi

usage_pattern="<!--- start usage output --->*<!--- end usage output --->"

readme="$(cat README.md)"
echo "${readme//$usage_pattern/$usag_sub}" > README.md
