#!/bin/sh
#/ script/goproject-tmpl builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/goproject-tmpl ./cmd/goproject-tmpl

exec bin/goproject-tmpl "$@"
