#!/bin/sh
#/ script/lint runs linters on the project.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

script/bindown -q install golangci-lint
script/bindown -q install shellcheck
bin/golangci-lint run ./...
bin/shellcheck script/*
