#!/bin/sh
#/ script/release-hook is run by release-train as pre-tag-hook

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

MODULE_NAME="$(go list -m)"
MAJOR_VERSION="$(echo "$RELEASE_VERSION" | cut -d. -f1)"
MODULE_VERSION_SUFFIX="$(echo "$MODULE_NAME" | grep -o '/v[0-9][0-9]*$' || true)"

# If MAJOR_VERSION >= 2, make sure the module name ends with `/v$MAJOR_VERSION`
if [ "$MAJOR_VERSION" -ge 2 ]; then
  if [ "$MODULE_VERSION_SUFFIX" != "/v$MAJOR_VERSION" ]; then
    echo "Module name must end with /v$MAJOR_VERSION"
    exit 1
  fi
else
  if [ -n "$MODULE_VERSION_SUFFIX" ]; then
    echo "Module name must not end with /v[0-9][0-9]*"
    exit 1
  fi
fi

# If there's no .goreleaser.yaml, there's nothing left to do.
[ -f ".goreleaser.yaml" ] || exit 0

script/bindown -q install goreleaser
git tag "$RELEASE_TAG"
bin/goreleaser release --clean --skip=publish
cp dist/checksums.txt dist/*.tar.gz "$ASSETS_DIR"
