name: applytemplate
on: [push]
jobs:
  applytemplate:
    runs-on: ubuntu-latest
    if: github.repository != 'WillAbides/goproject-tmpl' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: script/apply-template
      - uses: peter-evans/create-pull-request@v2
